version: 2
project_name: tether

before:
  hooks:
    - nix develop -c uv run --offline --no-managed-python --no-python-downloads --python python3 --script hack/release-scripts.py --version {{ .Version }} --all --output .release-extras
    - ./hack/generate.sh --check

builds:
  - id: tether
    main: ./cmd/tether
    binary: tether
    env:
      - CGO_ENABLED=0
    flags: [-trimpath]
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos: [darwin, linux]
    goarch: [amd64, arm64]
    ignore:
      - goos: darwin
        goarch: amd64
    ldflags:
      - -s -w -X main.version={{.Version}}
  - id: tsh
    main: ./cmd/tsh
    binary: tsh
    env:
      - CGO_ENABLED=0
    flags: [-trimpath]
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos: [darwin, linux]
    goarch: [amd64, arm64]
    ignore:
      - goos: darwin
        goarch: amd64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: tether
    ids: [tether, tsh]
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - LICENSE
      - README.md
      - src: completions/*
        dst: completions
      - src: schema/*.json
        dst: schema

checksum:
  name_template: checksums.txt

changelog:
  use: github-native

release:
  extra_files:
    - glob: .release-extras/*
